name: default-pipeline
on: push
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install cmake
        run: sudo apt-get -y install cmake
      - name: Build static library
        run: mkdir build && cd build && cmake .. -DTARGET_GROUP=build && make
      - name: Store build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: build/src/libhashing_static.a
          retention-days: 3
  
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install cmake
        run: sudo apt-get -y install cmake
      - name: Run tests
        run: mkdir build && cd build && cmake .. -DTARGET_GROUP=test && make && cd test && ctest -VV
      - name: Store test report
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: build/test/Testing/Temporary/LastTest.log
          retention-days: 3

  doxygen-docs-generate:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install doxygen
        run: sudo apt-get -y install doxygen
      - name: Generate doxygen documentation
        run: doxygen Doxyfile
      - name: Store doxygen documentation
        uses: actions/upload-artifact@v3
        with:
          name: doxygen-docs
          path: html
