name: default-pipeline
on: push
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install cmake
        run: sudo apt-get -y install cmake
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build static library
        run: mkdir build && cd build && cmake .. -DTARGET_GROUP=build && make
      - name: Store build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: build/src/libhashing_static.a
          retention-days: 3
  
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install cmake
        run: sudo apt-get -y install cmake
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run tests
        run: mkdir build && cd build && cmake .. -TARGET_GROUP=test && make && cd test && ctest
      - name: Store test raport
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: build/test/Testing/Temporary/LastTest.log
          retention-days: 3
    